[package]
name = "image-processor"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.25.2"
tokio = { version = "1.39.2", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
